version: '2.0'
services:
  wordpress:
    image: "wordpress:4.5.2-fpm"
    ports:
    - "9099:9000"
    volumes:
      - ./wordpress-data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    depends_on:
    - db
    networks:
    - blogUI


  db:
    image: 'mysql:5.7'
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    networks:
    - blogUI
    - dbUI

  dbadmin:
    image: 'phpmyadmin/phpmyadmin'
    ports:
    - "8088:80"
    links:
    - db
    networks:
    - dbUI

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
    - ./wordpress-data:/var/www/html:ro
    depends_on:
      - wordpress
      - dbadmin
    links:
      - wordpress
      - dbadmin
    networks:
      - blogUI
      - dbUI

volumes:
  wordpress-data:
    driver: local

networks:
  blogUI:
    driver: bridge
  dbUI:
    driver: bridge